using System;
using System.Text.Json.Serialization;

namespace Root.DTOs.UnavailabilityListComponents;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Reason {
	[JsonPropertyName("DRIVER_FUNERAL")]
	DRIVER_FUNERAL,

	[JsonPropertyName("DRIVER_HOLIDAY")]
	DRIVER_HOLIDAY,

	[JsonPropertyName("DRIVER_JOB_APPLICATION_LEAVE")]
	DRIVER_JOB_APPLICATION_LEAVE,

	[JsonPropertyName("DRIVER_LATE_START_EARLY_LEAVE")]
	DRIVER_LATE_START_EARLY_LEAVE,

	[JsonPropertyName("DRIVER_MEDICAL_EXAM")]
	DRIVER_MEDICAL_EXAM,

	[JsonPropertyName("DRIVER_OFF_SHIFT_PATTERN")]
	DRIVER_OFF_SHIFT_PATTERN,

	[JsonPropertyName("DRIVER_OTHER")]
	DRIVER_OTHER,

	[JsonPropertyName("DRIVER_PARENTAL_LEAVE")]
	DRIVER_PARENTAL_LEAVE,

	[JsonPropertyName("DRIVER_PUBLIC_HOLIDAY")]
	DRIVER_PUBLIC_HOLIDAY,

	[JsonPropertyName("DRIVER_RECUP")]
	DRIVER_RECUP,

	[JsonPropertyName("DRIVER_REDUCED_WORKING_HOURS_SCHEME")]
	DRIVER_REDUCED_WORKING_HOURS_SCHEME,

	[JsonPropertyName("DRIVER_SHIFT_PATTERN")]
	DRIVER_SHIFT_PATTERN,

	[JsonPropertyName("DRIVER_SICKNESS")]
	DRIVER_SICKNESS,

	[JsonPropertyName("DRIVER_SOCIAL_LEAVE")]
	DRIVER_SOCIAL_LEAVE,

	[JsonPropertyName("DRIVER_TEMPORARY_UNEMPLOYMENT")]
	DRIVER_TEMPORARY_UNEMPLOYMENT,

	[JsonPropertyName("DRIVER_TRAINING")]
	DRIVER_TRAINING,

	[JsonPropertyName("DRIVER_UNAUTHORISED_ABSENCE")]
	DRIVER_UNAUTHORISED_ABSENCE,

	[JsonPropertyName("DRIVER_UNION_LEAVE")]
	DRIVER_UNION_LEAVE,

	[JsonPropertyName("DRIVER_WORK_ACCIDENT")]
	DRIVER_WORK_ACCIDENT,

	[JsonPropertyName("VEHICLE_BRAKE_TEST")]
	VEHICLE_BRAKE_TEST,

	[JsonPropertyName("VEHICLE_CLEANING")]
	VEHICLE_CLEANING,

	[JsonPropertyName("VEHICLE_FRC_CERTIFICATE")]
	VEHICLE_FRC_CERTIFICATE,

	[JsonPropertyName("VEHICLE_HIRE")]
	VEHICLE_HIRE,

	[JsonPropertyName("VEHICLE_HYDRAULIC_INSPECTION")]
	VEHICLE_HYDRAULIC_INSPECTION,

	[JsonPropertyName("VEHICLE_INSPECTION")]
	VEHICLE_INSPECTION,

	[JsonPropertyName("VEHICLE_LIFT_OPS_EQUIP_REGULATIONS")]
	VEHICLE_LIFT_OPS_EQUIP_REGULATIONS,

	[JsonPropertyName("VEHICLE_MAINTENANCE")]
	VEHICLE_MAINTENANCE,

	[JsonPropertyName("VEHICLE_MOT_TEST")]
	VEHICLE_MOT_TEST,

	[JsonPropertyName("VEHICLE_OFF_ROAD")]
	VEHICLE_OFF_ROAD,

	[JsonPropertyName("VEHICLE_OTHER")]
	VEHICLE_OTHER,

	[JsonPropertyName("VEHICLE_PRESSURE_TEST")]
	VEHICLE_PRESSURE_TEST,

	[JsonPropertyName("VEHICLE_REPAIR")]
	VEHICLE_REPAIR,

	[JsonPropertyName("VEHICLE_SERVICE")]
	VEHICLE_SERVICE,

	[JsonPropertyName("VEHICLE_TACHOGRAPH_CALIBRATION")]
	VEHICLE_TACHOGRAPH_CALIBRATION,

	[JsonPropertyName("SUBCONTRACTOR_HOLIDAY")]
	SUBCONTRACTOR_HOLIDAY,

	[JsonPropertyName("SUBCONTRACTOR_SICKNESS")]
	SUBCONTRACTOR_SICKNESS,

	[JsonPropertyName("SUBCONTRACTOR_OTHER")]
	SUBCONTRACTOR_OTHER
}
